#!/usr/bin/env bash
DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.bash_profile
ln -s $DOTFILES/.bash_profile $HOME/.bash_profile

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.inputrc
ln -s $DOTFILES/.inputrc $HOME/.inputrc

source $HOME/.bash_profile

# Load local settings if they exist
if [ -f "$DOTFILES/.env.local" ]; then
    source "$DOTFILES/.env.local"
fi

# Git Config
if [ -n "$GIT_USER_EMAIL" ]; then
    git config --global user.email "$GIT_USER_EMAIL"
fi

if [ -n "$GIT_USER_NAME" ]; then
    git config --global user.name "$GIT_USER_NAME"
fi

git config --global credential.helper store

# Run installers
"$DOTFILES/installers/ubuntu-setup.sh"
"$DOTFILES/installers/php-environment.sh"
"$DOTFILES/installers/js-environment.sh"
"$DOTFILES/installers/go.sh"
"$DOTFILES/installers/composer.sh"
"$DOTFILES/installers/lazygit.sh"

exec bash -l