#!/usr/bin/env bash
DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.bash_profile
ln -s $DOTFILES/.bash_profile $HOME/.bash_profile

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -rf $HOME/.inputrc
ln -s $DOTFILES/.inputrc $HOME/.inputrc

source $HOME/.bash_profile

git config --global user.email ""
git config --global user.name ""
# Git Config
git config --global credential.helper store

#   # Godot things
#   https://gist.github.com/lucasecdb/2baf6d328a10d7fea9ec085d868923a0
